-- KRIKAL SQL schema reference (backend)
CREATE TABLE Sales (
  SaleID BIGINT PRIMARY KEY IDENTITY,
  InvoiceNo NVARCHAR(50) NOT NULL UNIQUE,
  SaleDate DATE NOT NULL,
  CustomerID BIGINT NULL,
  TotalAmount DECIMAL(18,2) NOT NULL,
  PaymentStatus NVARCHAR(20) NOT NULL,
  PaymentMode NVARCHAR(30) NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);

CREATE TABLE SaleItems (
  SaleItemID BIGINT PRIMARY KEY IDENTITY,
  SaleID BIGINT NOT NULL,
  ProductID NVARCHAR(100) NOT NULL,
  Qty DECIMAL(18,3) NOT NULL,
  Rate DECIMAL(18,2) NOT NULL,
  LineTotal DECIMAL(18,2) NOT NULL,
  FOREIGN KEY (SaleID) REFERENCES Sales(SaleID)
);

CREATE TABLE StockMovement (
  MovementID BIGINT PRIMARY KEY IDENTITY,
  MovementDate DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
  SourceType NVARCHAR(30) NOT NULL,
  SourceID BIGINT NOT NULL,
  ProductID NVARCHAR(100) NOT NULL,
  QtyChange DECIMAL(18,3) NOT NULL,
  Remarks NVARCHAR(255) NULL
);

CREATE TABLE CustomerLedger (
  LedgerID BIGINT PRIMARY KEY IDENTITY,
  CustomerID BIGINT NULL,
  SourceType NVARCHAR(30) NOT NULL,
  SourceID BIGINT NOT NULL,
  Debit DECIMAL(18,2) NOT NULL DEFAULT 0,
  Credit DECIMAL(18,2) NOT NULL DEFAULT 0,
  EntryDate DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);
